import type { TransactionListItem } from '../types/transactionsList';

export const ALL_TRANSACTIONS: TransactionListItem[] = [
  {
    id: 'TXN-2025-0891',
    type: 'top_up',
    status: 'completed',
    statusLabel: 'Completed',
    title: 'Wallet Top-Up via Stripe',
    sub: 'Mastercard ••••4242 · Eric Nelson',
    date: 'Mar 7, 2025 09:14 AM',
    amount: 500,
    sign: '+',
    detail: {
      processed: 'Stripe Payments Ltd',
      fee: '$7.30 (1.4% + $0.30)',
      net: '$492.70 deposited',
      currency: 'USD',
      country: 'Nigeria (billing)',
    },
  },
  {
    id: 'ESC-2025-0042',
    type: 'escrow',
    status: 'held',
    statusLabel: 'Held',
    title: 'Escrow Lock – Pediatric Surgeon, Lagos',
    sub: 'Tee-Company Ltd · Range $60k–$75k · Midpoint $67,500',
    date: 'Mar 6, 2025 02:30 PM',
    amount: 10125,
    sign: '-',
    job: 'Pediatric Surgeon',
    detail: {
      rate: '15% (Global South)',
      range: '$60,000–$75,000',
      midpoint: '$67,500',
      escrow: '$10,125 (15% × $67,500)',
      tier: 'Tier 1 – USAID benchmark verified',
      trueup: 'Pending hire confirmation',
    },
  },
  {
    id: 'TU-2025-0008',
    type: 'trueup_charge',
    status: 'pending',
    statusLabel: 'Pending',
    title: 'True-Up Charge – Global Health Research',
    sub: 'Actual $75,000 vs midpoint $70,000 · $750 owed',
    date: 'Mar 6, 2025 04:00 PM',
    amount: 750,
    sign: '$',
    job: 'Global Health Research',
    detail: {
      range: '$60,000–$80,000',
      midpoint: '$70,000',
      escrow: '$10,500',
      actual: '$75,000',
      final_fee: '$11,250',
      trueup: '$750 owed (within declared range)',
      window: '24h from hire confirmation',
      charge: 'Mastercard ••••4242',
    },
  },
  {
    id: 'ALN-2025-0015',
    type: 'alignment',
    status: 'pending',
    statusLabel: 'Pending',
    title: 'Alignment Fee – Dr. Amara Osei (2nd session)',
    sub: 'Public Health Advisor · session 2 of 2',
    date: 'Mar 5, 2025 03:00 PM',
    amount: 150,
    sign: '-',
    job: 'Public Health Advisor',
    detail: {
      candidate: 'Dr. Amara Osei',
      session: '2nd additional alignment session',
      role: 'Public Health Advisor',
      org: 'Medics Without Limits',
      decision: 'Awaiting employer decision',
      refund: 'Full $150 refunded on hire · Forfeited if invalid rejection',
    },
  },
  {
    id: 'ALN-2025-0014',
    type: 'alignment',
    status: 'pending',
    statusLabel: 'Pending',
    title: 'Alignment Fee – Priya Sharma (1st session)',
    sub: 'Senior Epidemiologist · session 1',
    date: 'Mar 5, 2025 11:00 AM',
    amount: 150,
    sign: '-',
    job: 'Senior Epidemiologist',
    detail: {
      candidate: 'Priya Sharma',
      session: '1st additional alignment session',
      role: 'Senior Epidemiologist',
      org: 'GlobalHealth Corp',
      decision: 'Awaiting employer decision',
      refund: 'Full $150 refunded on hire',
    },
  },
  {
    id: 'TU-2025-0006',
    type: 'trueup_credit',
    status: 'refunded',
    statusLabel: 'Refunded',
    title: 'True-Up Credit – Epidemiologist Nairobi',
    sub: '$62k actual < $70k midpoint → $1,200 returned',
    date: 'Mar 3, 2025 10:00 AM',
    amount: 1200,
    sign: '+',
    job: 'Epidemiologist',
    detail: {
      range: '$60,000–$80,000',
      midpoint: '$70,000',
      escrow: '$10,500',
      actual: '$62,000',
      final_fee: '$9,300',
      credit: '$1,200 returned to wallet',
      processed: 'Auto-refunded within 24h of hire',
    },
  },
  {
    id: 'ESC-2025-0039',
    type: 'escrow',
    status: 'held',
    statusLabel: 'Held',
    title: 'Escrow Lock – Public Health Advisor, Accra (Contract)',
    sub: 'Medics Without Limits · 6mo min. deposit · $5k/mo',
    date: 'Feb 22, 2025 01:45 PM',
    amount: 4500,
    sign: '-',
    job: 'Public Health Advisor',
    detail: {
      rate: '15% (Global South)',
      type: 'Contract 6–12 months',
      rate_monthly: '$5,000/month',
      min_tenure: '6 months',
      escrow: '$4,500 (15% × $30,000 min.)',
      tier: 'Tier 2 – Ghana regional proxy',
      trueup: 'Completion declaration required at contract end',
    },
  },
  {
    id: 'ALN-2025-0012',
    type: 'refund',
    status: 'completed',
    statusLabel: 'Completed',
    title: 'Alignment Fee Refund – Dr. Yusuf Ibrahim (Hired)',
    sub: 'Hire confirmed · Full $150 auto-refunded',
    date: 'Mar 1, 2025 10:00 AM',
    amount: 150,
    sign: '+',
    job: 'Infectious Disease Specialist',
    detail: {
      candidate: 'Dr. Yusuf Ibrahim',
      outcome: 'Hired',
      original_ref: '#ALN-2025-0009',
      refund_reason: 'Hire confirmed at 10:00 AM Mar 1',
      processed: 'Automatic · VORA escrow engine',
    },
  },
  {
    id: 'ALN-2025-0010',
    type: 'alignment',
    status: 'failed',
    statusLabel: 'Forfeited',
    title: 'Alignment Fee Forfeited – Dr. Kofi Mensah (Invalid Rejection)',
    sub: 'Rejection reason not documented · Fee forfeited · Flagged',
    date: 'Feb 25, 2025 02:00 PM',
    amount: 150,
    sign: '-',
    job: 'Biostatistician',
    detail: {
      candidate: 'Dr. Kofi Mensah',
      outcome: 'Rejected – reason invalid',
      reason_submitted: 'Personal fit',
      vora_review: 'VORA reviewed: reason insufficient',
      flag: '⚠ Employer account flagged (1/3 warnings)',
      forfeited: '$150.00 forfeited · candidate compensated',
    },
  },
  {
    id: 'TXN-2025-0865',
    type: 'top_up',
    status: 'completed',
    statusLabel: 'Completed',
    title: 'Wallet Top-Up via Paystack',
    sub: 'GTBank · +234 8012 345678 · NGN conversion',
    date: 'Feb 20, 2025 08:30 AM',
    amount: 1000,
    sign: '+',
    detail: {
      processed: 'Paystack Inc.',
      channel: 'GTBank card (Verve)',
      currency: 'NGN → USD at 1,620 NGN/USD',
      fee: '1.5% local Paystack rate',
      net: '$985 deposited',
    },
  },
  {
    id: 'WD-2025-0042',
    type: 'withdrawal',
    status: 'completed',
    statusLabel: 'Completed',
    title: 'Withdrawal – Bank Transfer (Barclays UK)',
    sub: 'Access Bank ••••7823 · 2 business days',
    date: 'Feb 18, 2025 11:00 AM',
    amount: 500,
    sign: '-',
    detail: {
      method: 'Bank Transfer',
      bank: 'Access Bank Nigeria',
      account: '••••7823',
      processing: '1–2 business days',
      fee: 'Free',
      arrived: 'Feb 19, 2025',
    },
  },
  {
    id: 'ESC-2025-0031',
    type: 'escrow',
    status: 'completed',
    statusLabel: 'Completed',
    title: 'Escrow Released – Epidemiologist Nairobi (Hired)',
    sub: 'GlobalHealth Corp · Final fee $9,300 · Hire confirmed',
    date: 'Mar 3, 2025 09:50 AM',
    amount: 9300,
    sign: '-',
    job: 'Epidemiologist',
    detail: {
      final_fee: '$9,300 (15% × $62,000)',
      escrow_held: '$10,500',
      credit_returned: '$1,200',
      status: 'Released on hire confirmation',
      hired: 'Dr. Priya Sharma · Mar 3, 2025',
    },
  },
];

export const TRANSACTION_TYPE_FILTER_OPTIONS = [
  { label: 'All types', value: '' },
  { label: 'Top-ups', value: 'top_up' },
  { label: 'Escrow Locks', value: 'escrow' },
  { label: 'True-Up Charges', value: 'trueup_charge' },
  { label: 'True-Up Credits', value: 'trueup_credit' },
  { label: 'Alignment Fees', value: 'alignment' },
  { label: 'Refunds', value: 'refund' },
  { label: 'Withdrawals', value: 'withdrawal' },
];

export const TRANSACTION_STATUS_FILTER_OPTIONS = [
  { label: 'All statuses', value: '' },
  { label: 'Completed', value: 'completed' },
  { label: 'Pending', value: 'pending' },
  { label: 'Held', value: 'held' },
  { label: 'Refunded', value: 'refunded' },
  { label: 'Failed', value: 'failed' },
];

export const TRANSACTION_DATE_FILTER_OPTIONS = [
  { label: 'All time', value: '' },
  { label: 'Last 7 days', value: '7' },
  { label: 'Last 30 days', value: '30' },
  { label: 'Last 90 days', value: '90' },
];

export const TRANSACTIONS_PER_PAGE = 8;
